version: "3.3"
services:
  app:
    build: .
    image: bwilfong122/video_app:latest
    environment:
      - DB_PASSWORD=${DB_PASSWORD} 
      - DropBox_Access_Token=${DropBox_Access_Token}
    ports:
      - "80:80"
